language: go
go:
  - tip

os:
  - linux
  - osx

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/toolssss/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -repotoken 3gHdORO5k5ziZcWMBxnd9LrMZaJs8m9x5
